In [8]:
import pandas as pd
from tensorflow.keras.preprocessing.sequence import TimeseriesGenerator
import numpy as np

# Sample data (replace with your own dataframe)
data = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', periods=100),
    'Close': np.arange(1,101,1)
})

lookback = 10
target_day = 3
batch_size = 32

# Convert 'Close' column to numpy array
data_array = data['Close'].values

# Adjust the length parameter to include the lookback period and the target day
length = lookback + target_day

# Generate input-output pairs using TimeseriesGenerator
generator = TimeseriesGenerator(data_array, data_array, length=length, batch_size=batch_size)


    
# Print the generated input-output pairs
for i in range(len(generator)):
    inputs, targets = generator[i]
    print("Input sequence:", inputs)
    print("Target value:", targets)  # Print the last value of each sequence (T+3)
    print("---")

Input sequence: [[ 1  2  3  4  5  6  7  8  9 10 11 12 13]
 [ 2  3  4  5  6  7  8  9 10 11 12 13 14]
 [ 3  4  5  6  7  8  9 10 11 12 13 14 15]
 [ 4  5  6  7  8  9 10 11 12 13 14 15 16]
 [ 5  6  7  8  9 10 11 12 13 14 15 16 17]
 [ 6  7  8  9 10 11 12 13 14 15 16 17 18]
 [ 7  8  9 10 11 12 13 14 15 16 17 18 19]
 [ 8  9 10 11 12 13 14 15 16 17 18 19 20]
 [ 9 10 11 12 13 14 15 16 17 18 19 20 21]
 [10 11 12 13 14 15 16 17 18 19 20 21 22]
 [11 12 13 14 15 16 17 18 19 20 21 22 23]
 [12 13 14 15 16 17 18 19 20 21 22 23 24]
 [13 14 15 16 17 18 19 20 21 22 23 24 25]
 [14 15 16 17 18 19 20 21 22 23 24 25 26]
 [15 16 17 18 19 20 21 22 23 24 25 26 27]
 [16 17 18 19 20 21 22 23 24 25 26 27 28]
 [17 18 19 20 21 22 23 24 25 26 27 28 29]
 [18 19 20 21 22 23 24 25 26 27 28 29 30]
 [19 20 21 22 23 24 25 26 27 28 29 30 31]
 [20 21 22 23 24 25 26 27 28 29 30 31 32]
 [21 22 23 24 25 26 27 28 29 30 31 32 33]
 [22 23 24 25 26 27 28 29 30 31 32 33 34]
 [23 24 25 26 27 28 29 30 31 32 33 34 35]
 [24 25 26 27 28 2

In [48]:
data = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', periods=100),
    'Close': np.arange(1,101,1)
})
data_array = data['Close'].values
look_back = 10
forward = 5
train = TimeseriesGenerator(data_array, data_array, length=look_back + forward-1, batch_size=len(data_array))
X_train,y_train = list(train)[0][0][:,:look_back], list(train)[0][1]
X_train,y_train

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
        [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
        [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
        [16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
        [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
        [19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],


In [47]:
list(train)[0]

(array([[ 1,  2,  3, ..., 12, 13, 14],
        [ 2,  3,  4, ..., 13, 14, 15],
        [ 3,  4,  5, ..., 14, 15, 16],
        ...,
        [84, 85, 86, ..., 95, 96, 97],
        [85, 86, 87, ..., 96, 97, 98],
        [86, 87, 88, ..., 97, 98, 99]]),
 array([ 15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,  27,
         28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,
         41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,
         54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,  66,
         67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,
         80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,  92,
         93,  94,  95,  96,  97,  98,  99, 100]))

In [33]:
data = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', periods=100),
    'Close': np.arange(1,101,1)
})
data_array = data['Close'].values
look_back = 10
forward = 5
train = TimeseriesGenerator(data_array[:-forward+1], data_array[forward-1:], length=look_back, batch_size=len(data_array))
X_train,y_train = list(train)[0][0], list(train)[0][1]
X_train,y_train

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
        [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
        [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
        [16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
        [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
        [19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],


In [27]:
data_array[:-forward+1]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96])

In [36]:
list(train)

[(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
         [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
         [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
         [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
         [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
         [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
         [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
         [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
         [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
         [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
         [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
         [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
         [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
         [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
         [16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
         [17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
         [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
         [19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
         [20, 21, 22, 23, 24, 2

In [50]:
data = pd.DataFrame({
    'Date': pd.date_range(start='2023-01-01', periods=100),
    'Close': np.arange(1,101,1)
})
data_array = data['Close'].values
train = TimeseriesGenerator(data_array, data_array, length=10, batch_size=1000)
X_train,y_train = list(train)[0][0], list(train)[0][1]
X_train,y_train

(array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
        [ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15],
        [ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
        [ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17, 18],
        [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
        [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
        [12, 13, 14, 15, 16, 17, 18, 19, 20, 21],
        [13, 14, 15, 16, 17, 18, 19, 20, 21, 22],
        [14, 15, 16, 17, 18, 19, 20, 21, 22, 23],
        [15, 16, 17, 18, 19, 20, 21, 22, 23, 24],
        [16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
        [17, 18, 19, 20, 21, 22, 23, 24, 25, 26],
        [18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
        [19, 20, 21, 22, 23, 24, 25, 26, 27, 28],
        [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
